CREATE TABLE ep2.PERSON (
	ID		NUMERIC(4),
	PERSON		VARCHAR(20),
	
	CONSTRAINT per_pk PRIMARY KEY (ID)
);

CREATE TABLE ep2.PERSON_FRIEND (
	PERSONID		NUMERIC(4),
	FRIENDID		NUMERIC(4),

	CONSTRAINT pf_pk PRIMARY KEY (PERSONID, FRIENDID),

	CONSTRAINT pfp_fk FOREIGN KEY (PERSONID)
		REFERENCES ep2.PERSON (ID),

	CONSTRAINT pff_fk FOREIGN KEY (FRIENDID)
		REFERENCES ep2.PERSON (ID)
);