DROP TABLE IF EXISTS EMPLOYEE CASCADE;
DROP TABLE IF EXISTS DEPARTMENT CASCADE;
DROP TABLE IF EXISTS PROJECT CASCADE;
DROP TABLE IF EXISTS WORKSON CASCADE;
DROP TABLE IF EXISTS DEPENDENT CASCADE;

CREATE TABLE EMPREGADO (
	PNOME		VARCHAR(20),
	MNOME		CHAR,
	LNOME		VARCHAR(20),
	NSS			CHAR(9),
	DATANASC		DATE,
	ENDERECO		VARCHAR(30),
	SEXO		CHAR(1),
	SALARIO		NUMERIC(5),
	NSSUPER	CHAR(9),
	NDEP			NUMERIC(1),

	CONSTRAINT emp_pk PRIMARY KEY (NSS)

);

CREATE TABLE DEPARTAMENTO (
	DNOME			VARCHAR(20),
	DNUMERO			NUMERIC(1),
	NSSGER			CHAR(9),
	DATAINICGER	DATE,

	CONSTRAINT dep_pk PRIMARY KEY (DNUMERO),

	CONSTRAINT dep_mg_fk FOREIGN KEY (NSSGER)
		REFERENCES EMPREGADO (NSS)
);

CREATE TABLE PROJETO (
	PNOME		VARCHAR(20),
	PNUMERO		NUMERIC(2),
	PLOCALIZACAO VARCHAR(20),
	DNUM        NUMERIC(1),

	CONSTRAINT proj_pk PRIMARY KEY (PNUMERO)
);

CREATE TABLE TRABALHAEM (
	NSSEMP	CHAR(9),
	PNRO		NUMERIC(3),
	HORAS	NUMERIC(3,1),

	CONSTRAINT wrkon_pk PRIMARY KEY (NSSEMP, PNRO),

	CONSTRAINT wrkon_essn_fk FOREIGN KEY (NSSEMP)
		REFERENCES EMPREGADO (NSS),

	CONSTRAINT wrkon_pno_fk FOREIGN KEY (PNRO)
		REFERENCES PROJETO(PNUMERO)
);

CREATE TABLE DEPENDENTE (
	NSSEMP			CHAR(9),
	NOMEDEPENDENTE	VARCHAR(20),
	SEXO				CHAR(1),
	DATANIV			DATE,
	RELACAO	VARCHAR(10),

	CONSTRAINT dnt_pk PRIMARY KEY (NSSEMP, NOMEDEPENDENTE),

	CONSTRAINT dnt_essn_fk FOREIGN KEY (NSSEMP)
		REFERENCES EMPREGADO (NSS)
);