CREATE TABLE ep1.USUARIO (
	CPF		NUMERIC(11),
	ENDERECO		VARCHAR(40),
	LOGIN		VARCHAR(20),
	NOME			VARCHAR(20),
	SENHA		VARCHAR(30),
	INSTITUICAO		VARCHAR(20),
	D_NASCIMENTO		DATE,
	
	CONSTRAINT usu_pk PRIMARY KEY (CPF)
);

CREATE TABLE ep1.PERFIL (
	CODIGO_PERFIL	NUMERIC(2),
	FUNCAO		VARCHAR(20),
	
	CONSTRAINT per_pk PRIMARY KEY (CODIGO_PERFIL)
);

CREATE TABLE ep1.SERVICO (
	CODIGO		NUMERIC(2),
	TIPO		CHAR(1),
	DESCRICAO		VARCHAR(50),
	
	CONSTRAINT ser_pk PRIMARY KEY (CODIGO)
);

CREATE TABLE ep1.PACIENTE (
	CPF_PACIENTE		NUMERIC(11),
	NOME		VARCHAR(20),
	D_NASCIMENTO		DATE,
	ENDERECO	VARCHAR(40),
	
	CONSTRAINT pac_pk PRIMARY KEY (CPF_PACIENTE)
);

CREATE TABLE ep1.AMOSTRA (
	TIME_COLETA		TIMESTAMP,
	MATERIAL		VARCHAR(20),
	CPF_PACIENTE	NUMERIC(11),
	
	CONSTRAINT amo_pk PRIMARY KEY (TIME_COLETA, MATERIAL, CPF_PACIENTE)
);

CREATE TABLE ep1.EXAME (
	TIME_COLETA		TIMESTAMP,
	MATERIAL		VARCHAR(20),
	CPF_PACIENTE	NUMERIC(11),
	TIPO		BOOLEAN,
	VIRUS		VARCHAR(20),
	
	CONSTRAINT exa_pk PRIMARY KEY (TIME_COLETA, MATERIAL, CPF_PACIENTE, TIPO, VIRUS)
);

CREATE TABLE ep1.A_PESQUISA (
	CODIGO_A_PESQUISA		NUMERIC(2),
	A_PESQUISA		VARCHAR(20),
	
	CONSTRAINT ape_pk PRIMARY KEY (CODIGO_A_PESQUISA)
);

CREATE TABLE ep1.TUTELADO_POR (
	CPF_TUTELADO		NUMERIC(11),
	ACESSO_SERVICO		NUMERIC(2),
	CPF_TUTOR		NUMERIC(11),
	
	CONSTRAINT tut_pk PRIMARY KEY (CPF_TUTELADO, ACESSO_SERVICO),

	CONSTRAINT tut_cpf_fk FOREIGN KEY (CPF_TUTELADO)
		REFERENCES ep1.USUARIO (CPF),

	CONSTRAINT tut_as_fk FOREIGN KEY (ACESSO_SERVICO)
		REFERENCES ep1.SERVICO (CODIGO),

	CONSTRAINT tut_cpfsup_fk FOREIGN KEY (CPF_TUTOR)
		REFERENCES ep1.USUARIO(CPF)
);

CREATE TABLE ep1.PERTENCE (
	CPF		NUMERIC(11),
	CODIGO_PERFIL		NUMERIC(2),
	
	CONSTRAINT pet_pk PRIMARY KEY (CPF, CODIGO_PERFIL),

	CONSTRAINT pet_cpf_fk FOREIGN KEY (CPF)
		REFERENCES ep1.USUARIO (CPF),

	CONSTRAINT pet_cp_fk FOREIGN KEY (CODIGO_PERFIL)
		REFERENCES ep1.PERFIL(CODIGO_PERFIL)
);

CREATE TABLE ep1.USUARIO_AREA (
	CPF		NUMERIC(11),
	CODIGO_A_PESQUISA		NUMERIC(2),
	
	CONSTRAINT usua_pk PRIMARY KEY (CPF, CODIGO_A_PESQUISA),

	CONSTRAINT usua_cpf_fk FOREIGN KEY (CPF)
		REFERENCES ep1.USUARIO (CPF),

	CONSTRAINT usua_cap_fk FOREIGN KEY (CODIGO_A_PESQUISA)
		REFERENCES ep1.A_PESQUISA(CODIGO_A_PESQUISA)
);

CREATE TABLE ep1.ACESSO_A (
	CODIGO_PERFIL	NUMERIC(2),
	ACESSO_SERVICOS		NUMERIC(2),

	CONSTRAINT ace_pk PRIMARY KEY (CODIGO_PERFIL, ACESSO_SERVICOS),

	CONSTRAINT ace_cp_fk FOREIGN KEY (CODIGO_PERFIL)
		REFERENCES ep1.PERFIL(CODIGO_PERFIL),

	CONSTRAINT ace_as_fk FOREIGN KEY (ACESSO_SERVICOS)
		REFERENCES ep1.SERVICO(CODIGO)
);

CREATE TABLE ep1.UTILIZA (
	HORARIO		TIMESTAMP,
	CPF		NUMERIC(11),
	CODIGO_PERFIL_P	NUMERIC(2),
	CODIGO_SERVICO	NUMERIC(1),
	CODIGO_PERFIL_S	NUMERIC(2),

	CONSTRAINT uti_pk PRIMARY KEY (HORARIO, CPF, CODIGO_PERFIL_P),

	CONSTRAINT uti_cpf_cpp_fk FOREIGN KEY (CPF, CODIGO_PERFIL_P)
		REFERENCES ep1.PERTENCE (CPF, CODIGO_PERFIL),

	CONSTRAINT uti_cs_cps_fk FOREIGN KEY (CODIGO_PERFIL_S, CODIGO_SERVICO)
		REFERENCES ep1.ACESSO_A(CODIGO_PERFIL, ACESSO_SERVICOS)
);

CREATE TABLE ep1.ATENDE (
	CODIGO_ATENDE	BIGINT,
	CPF_PACIENTE		NUMERIC(11),
	CPF_USUARIO		NUMERIC(11),

	CONSTRAINT ate_pk PRIMARY KEY (CODIGO_ATENDE, CPF_PACIENTE),

	CONSTRAINT ate_cpfp_fk FOREIGN KEY (CPF_PACIENTE)
		REFERENCES ep1.PACIENTE(CPF_PACIENTE),

	CONSTRAINT ate_cpfu_fk FOREIGN KEY (CPF_USUARIO)
		REFERENCES ep1.USUARIO(CPF)
);